import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../common/styles/Home.module.scss'
import Graph from '../components/Graph'
import Layout from '../components/Layout'
import Newslist from '../components/Newslist'
import Tasks from '../components/Tasks'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CRM app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
      <Newslist />
      <Graph />
      <Tasks />

    </div>
  )
}

export default Home
